name: Update sub3.txt every 30 min

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Show current directory
      run: |
        pwd
        ls -la
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install requests
      run: pip install requests
    
    - name: Generate sub3.txt
      run: python generate_sub3.py
    
    - name: Commit & Push
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add sub3.txt
        git diff --staged --quiet || (git commit -m "🔄 sub3.txt | $(date +'%H:%M')" && git push)
